name: Daily Weather Report

on:
  schedule:
    - cron: "0 21 * * *"  # 한국 시간 기준 오전 6시
  push:
    branches:
      - main

jobs:
  weather:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Python 설정
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: 의존성 설치
        run: pip install requests pytest

      - name: 날씨 API 테스트 실행
        run: pytest test_weather_api.py

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.naver.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "GitHub Actions Test"
          body: "Hello, this is a test email!"
          to: "jschang0407@naver.com"
          from: ${{ secrets.EMAIL_USER }}
#          attachments: weather_result.json
